from crewai import Agent, Task
from Custom_Tools.custom_tool import tools1
from Custom_Tools.custom_tool2 import tools2
from Custom_Tools.custom_tool3 import tools3


def agent1(llm) -> Agent:
    return Agent(
        role="AnalyzerAgent",
        goal=(
            "Process the data.csv file from the Inputs directory using the custom_tool1. "
            "Analyze and categorize students into pass/fail based on subject scores and attendance. "
            "Save the categorized results as CSV files in the Outputs folder."
        ),
        backstory=(
            "You are a Data Analyst agent specializing in student performance analysis. "
            "You use the provided custom tool to load datasets, perform statistical analysis, "
            "and generate comprehensive reports. Your expertise lies in identifying patterns "
            "and categorizing students based on academic performance and attendance metrics."
        ),
        llm=llm,
        tools=[tools1],
        verbose=True,
        allow_delegation=False  # Added this to prevent the agent from trying to delegate
    )


def agent2(llm) -> Agent:
    return Agent(
        role="MailSenderAgent",
        goal=(
            "Send congratulatory emails to parents of students who passed all subjects "
            "and maintained attendance above 80%."
        ),
        backstory=(
            "You are an AI email automation agent working in a school system. "
            "Your responsibility is to send personalized congratulatory emails to parents "
            "of students who passed all subjects and maintained attendance above 80%. "
            "You use the provided custom_tool2 to efficiently send emails to all eligible parents."
        ),
        verbose=True,
        llm=llm,
        tools=[tools2],
        allow_delegation=False
    )


def agent3(llm) -> Agent:
    return Agent(
        role="WarningMailSenderAgent",
        goal=(
            "Send warning emails to parents of students who failed to meet academic "
            "or attendance criteria, clearly specifying the reasons for concern."
        ),
        backstory=(
            "You are an AI email automation agent responsible for student welfare monitoring. "
            "Your duty is to inform parents about their child's academic or attendance issues "
            "with detailed, constructive feedback. You analyze failure reasons (low marks, "
            "poor attendance, or both) and send personalized warning emails with clear "
            "information about consequences if improvements are not made. "
            "You use custom_tool3 to send these important communications."
        ),
        verbose=True,
        llm=llm,
        tools=[tools3],
        allow_delegation=False
    )

def agent4(llm) -> Agent:
    return Agent(
        role="ReportGeneratorAgent",
        goal=(
            "Generate a comprehensive student performance report for submission to HOD/Principal. "
            "You must strictly use the outputs generated by the previous agents and tasks."
        ),
        backstory=(
            "You are an expert report writer specializing in educational analytics. "
            "Your job is to create a professional and insightful report for school management. "
            "Use the results produced by Task1, Task2, and Task3 as the primary input for generating the final report."
        ),
        verbose=True,
        llm=llm,
        allow_delegation=True
    )
