from crewai import Task
from Crew_Agents.agents import agent1
from Crew_Agents.agents import agent2
from Crew_Agents.agents import agent3
from Crew_Agents.agents import agent4

def task1(llm) -> Task:
    return Task(
        name="Data Analyst",
        description=(
            "You are a data analyst AI agent specializing in dataset processing and analysis. "
            "Your main task is to analyze the student performance dataset. "
            "The dataset is given inside the Inputs dir as data.csv. "
            "You MUST use the provided custom tool named 'custom_tool1' to load, read, and process this dataset. "
            "Do not attempt to read or access files directly — always use the custom tool for all data operations. "
            "The tool will automatically: "
            "1. Load the dataset from Inputs/data.csv "
            "2. Identify students who pass all subjects (score >= 35) "
            "3. Check attendance is above 80% "
            "4. Generate two CSV files in the Outputs directory "
            "Simply call the tool and report its results."
        ),
        expected_output=(
            "A detailed summary report containing: "
            "- Total number of students analyzed "
            "- Number of students who passed all subjects with 80%+ attendance "
            "- Number of students who failed the criteria "
            "- List of subjects that were analyzed "
            "- Confirmation that two CSV files were created: "
            "  1. pass_all_got_attendance_80.csv "
            "  2. fail_in_pass_or_attendance.csv"
        ),
        agent=agent1(llm),
    )


def task2(llm) -> Task:  # ✅ Changed parameter to llm instead of agent
    return Task(
        name="Mail Sender",
        description=(
            "Use the custom_tool2 to send congratulatory emails to parents of students "
            "in the name of school_name: {school_name} and examination: {examination}"
            "who passed all subjects and maintained 80% + attendance. "
            "The student data is available in the file 'pass_all_got_attendance_80.csv' "
            "located in the Outputs directory. "
            "You MUST use the provided custom tool named 'custom_tool2' to send the emails. "
            "Do not attempt to send emails directly — the tool handles everything automatically. "
            "Simply execute the tool and report the results."
        ),
        expected_output=(
            "A confirmation message indicating: "
            "- Total number of emails sent successfully "
            "- List of students/parents who received emails "
            "- Any errors encountered during the email sending process"
        ),
        agent=agent2(llm)  # ✅ Pass llm to agent2
    )


def task3(llm) -> Task:
    return Task(
        name="Warning Mail Sender",
        description=(
            "Use custom_tool3 to send warning emails to parents of students who failed "
            "in the name of school_name: {school_name} and examination: {examination}"
            "to meet the required criteria (passing all subjects AND maintaining 80%+ attendance). "
            "The data is available in 'fail_in_pass_or_attendance.csv' in the Outputs directory. "
            "The tool will automatically: "
            "1. Read the fail CSV file "
            "2. Analyze why each student failed (attendance, marks, or both) "
            "3. Generate personalized warning emails with specific details "
            "4. Include warnings about future consequences "
            "5. Send emails to all parents "
            "You MUST use custom_tool3 - do not attempt to send emails directly."
        ),
        expected_output=(
            "A detailed report containing: "
            "- Total number of warning emails sent "
            "- Breakdown of failure reasons (attendance issues, subject failures, both) "
            "- List of students who received warning emails with their specific issues "
            "- Confirmation that all emails were sent successfully"
        ),
        agent=agent3(llm)
    )

def task4(llm) -> Task:
    return Task(
        name="Comprehensive Report Generator",
        description=(
            "Create a detailed student performance report for HOD/Principal. "
            "STRICT RULE: You must use the outputs generated by Task1, Task2, and Task3. "
            "Base your analysis and report content entirely on those processed results.\n\n"

            "Your task:\n"
            "1. Perform analysis and derive meaningful insights.\n"
            "2. Provide recommendations:\n"
            "   - Immediate actions for struggling students\n"
            "   - Subject-specific interventions\n"
            "   - Attendance improvement strategies\n"
            "   - Resource allocation suggestions\n"
            "   - Parent-teacher meeting recommendations\n\n"
            "7. Give a clear conclusion.\n\n"
            "Store the final report in 'report.md'."
        ),
        expected_output=(
            "A clear report with:\n"
            "1. Summary\n"
            "2. Subject performance section\n"
            "3. Attendance analysis\n"
            "4. Actions taken summary\n"
            "5. Recommendations\n"
            "Length: 200-300 words\n"
            "Format: Markdown\n"
            "Tone: Professional"
        ),
        agent=agent4(llm),
        output_file="report.md",
        context=[task1(llm), task2(llm), task3(llm)],
    )
